const restList = [
  {
    rate:4.3,
    brand_id: 93,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/d758442b-293b-402c-9fef-c6325156a1ca.jpg",
    brand_name: "Big Wong",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    logo: "https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png",
    background_url: "https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png",
    main_offering: "Chinese",
    slug: "big-wong",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/ed5ae91c-b2a9-40ea-b3fd-1d8e82c74225.jpg",
  },
  {
    rate:3.3,
    brand_id: 92,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/dcd48237-4194-4d8f-a7b8-b0c82ea98172.jpg",
    brand_name: "Chinese Daily",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    logo: "https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png",
    background_url: "https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png",
    main_offering: "Asian",
    slug: "chinese-daily",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/4959cb60-6330-488a-9041-13829e540685.jpg",
  },
  {
    rate:4.5 ,
    brand_id: 29,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/e65c0247-812f-43da-92b6-f156fc32e764.jpg",
    brand_name: "Wendy's Burgers",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Stacked & packed for heavy duty",
    logo: "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
    main_offering: "Burger",
    slug: "wendy-s",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/0f5f9749-d568-4b0d-a0a1-0d05717b3032.jpg",
  },
  {
    rate: 2.5,
    brand_id: 168,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/9b5a7785-0dbd-4561-a20a-c0497337c38c.jpg",
    brand_name: "FRICKEN CHICKEN",
    brand_start_time: "11:00:00",
    brand_end_time: "03:00:00",
    description: "Fried Chicken, Fast Food, Burgers, Sandwiches",
    logo: "https://rp-media.faasos.io/catalog/images/MFT5GZZAT3TF.jpeg",
    rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/MFT5GZZAT3TF.jpeg",
    background_url:
      "https://rp-media.faasos.io/catalog/images/MFT5GZZAT3TF.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/MFT5GZZAT3TF.jpeg",
    main_offering: "Fried Chicken, Fast Food, Wings",
    slug: "fricken",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/93941896-78e0-4d89-9442-967bb0ee2068.jpg",
  },
  {
    rate: 3,
    brand_id: 176,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/4c6581c8-560b-49bc-bbf4-f3717aba07de.png",
    brand_name: "Prasuma Momo Kitchen",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Impossibly Delicious Momos ",
    logo: "https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg",
    rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg",
    background_url:
      "https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg",
    main_offering: "Momos",
    slug: "prasuma-momos",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/8471bb13-e93b-4a79-803b-8de2f8318035.jpg",
  },
  {
    rate: 5,
    brand_id: 55,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/dbd14ffe-3ef6-458a-b240-23b67fe3f79f.jpg",
    brand_name: "The Brooklyn Creamery",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Guilt Free Indulgent Ice Creams",
    logo: "https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png",
    background_url: "https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png",
    main_offering: "Ice Cream",
    slug: "the-brooklyn-creamery",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/57981af2-15c0-4d9c-a39f-753500625017.jpg",
  },
  {
    rate: 2,
    brand_id: 167,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/17af1be7-02b5-43f4-9014-1326c484c353.png",
    brand_name: "Pastonji Ice Cream and Desserts",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Ice Creams with a Warm Heart",
    logo: "https://rp-media.faasos.io/catalog/images/XZGMCZDSCMIO.jpeg",
    rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/XZGMCZDSCMIO.jpeg",
    background_url:
      "https://rp-media.faasos.io/catalog/images/XZGMCZDSCMIO.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/XZGMCZDSCMIO.jpeg",
    main_offering: "Ice Cream",
    slug: "pastonji-ice-cream",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/0f9a94b9-0a3a-46ec-bb72-b81888b5887c.jpg",
  },
  {
    rate:3.9,
    brand_id: 28,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/d6e0be21-aee6-4733-b27b-9c98f79b54cb.png",
    brand_name: "Slay Coffee",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Great Coffee. Everyday.",
    logo: "https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg",
    main_offering: "Coffee",
    slug: "slay-coffee",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/f03f9411-45bd-47b4-a1f3-8fc795ce267b.jpg",
  },
  {
    rate: 4,
    brand_id: 47,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/92bd394e-fa7b-4470-8d79-732f9f5fdd4b.jpg",
    brand_name: "Mad Over Donuts",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Bite into happiness",
    logo: "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
    background_url: "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
    main_offering: "Donuts",
    slug: "mad-over-donuts",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/4d205101-2a4c-444d-a5bd-64b10cee4e51.jpg",
  },
  {
    rate: 2.5,
    brand_id: 73,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/6584aea2-eedf-4016-8179-c5ed5e4abe11.jpg",
    brand_name: "Veg Daawat by Behrouz",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "A curated spread of royal veg biryanis & kebabs",
    logo: "https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg",
    main_offering: "Royal Biryani",
    slug: "veg-daawat-by-behrouz",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/e8a97c77-02a5-4060-94b1-e2be4e28acd8.jpg",
  },
  {
    rate: 3.3,
    brand_id: 20,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/ff45eb24-ff5d-49d5-8652-7f90aaee28f5.jpg",
    brand_name: "Faasos",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Indulgent wraps loaded with high protein fillings",
    logo: "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
    main_offering: "Wraps",
    slug: "faasos",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/fe33b3e9-6d55-4c2f-b6f5-a6c7ebeeabce.jpg",
  },
  {
    rate: 5,
    brand_id: 26,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/44df4975-8ff8-49dd-8e66-58d4d9a80a87.jpg",
    brand_name: "Behrouz Biryani",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Handcrafted, Royal Biryanis",
    logo: "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
    main_offering: "Royal Biryani",
    slug: "behrouz-biryani",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/eecae976-af37-4f0f-adfe-a5a68b401729.jpg",
  },
  {
    rate: 2,
    brand_id: 21,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/e85c7df9-03a7-4e7e-9aff-63777accdf57.jpg",
    brand_name: "Ovenstory",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Pizza with standout toppings",
    logo: "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    main_offering: "Pizzas",
    slug: "ovenstory",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/7b0d4930-5806-4ee3-97bd-b606932bbe64.jpg",
  },
  {
    rate: 5,
    brand_id: 23,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/dd79d385-5898-4956-8a07-718b8ddde9ff.jpg",
    brand_name: "Firangi Bake",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Safe & Legendary Bakes",
    logo: "https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg",
    main_offering: "Pasta & Lasagnas",
    slug: "firangi-bake",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/be6ab66f-c173-414c-889e-2600cac04268.jpg",
  },
  {
    rate: 1,
    brand_id: 24,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/56e8a229-4d1f-4afc-9217-d44b44299d15.jpg",
    brand_name: "Sweet Truth",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "The Purest Indulgence",
    logo: "https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg",
    main_offering: "Desserts",
    slug: "sweet-truth",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/57d56176-1f11-43af-8c7a-003b23aaacc8.png",
  },
  {
    rate: 4.1,
    brand_id: 30,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/a2963595-02b9-4472-80a5-e790d9308d93.jpg",
    brand_name: "The Good Bowl",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Delicious Bowl Meals - Hygienic & Safe",
    logo: "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
    main_offering: "Rice Bowl",
    slug: "the-good-bowl",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/233e155d-e498-4239-9013-7cb4c999d0ab.jpg",
  },
  {
    rate: 3,
    brand_id: 27,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/aa14227c-d477-423a-a7ef-8b8b2d15c56a.jpg",
    brand_name: "Lunchbox - Meals & Thalis",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Homestyle, Wholesome, Delightful",
    logo: "https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg",
    main_offering: "Homestyle Meals",
    slug: "lunchbox",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/ac77b7c5-fe82-4448-a9b1-d9fa9451479c.jpg",
  },
  {
    rate: 2,
    brand_id: 25,
    client_source_id: 13,
    banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/cbd4171c-dc9c-4ba4-96f8-ef4e4c3f959e.jpg",
    brand_name: "The Biryani Life",
    brand_start_time: "00:00:00",
    brand_end_time: "23:59:00",
    description: "Hyderabad & Lucknow Biryani experts",
    logo: "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
    rectangle_logo: "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
    background_url: "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
    background_url_large:
      "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
    main_offering: "Hyderabadi Biryani",
    slug: "the-biryani-life",
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [],
    store_front_brand_image_url:
      "https://product-assets.faasos.io/eatsure_cms/production/a5157179-7451-48b1-8797-b63aac29573d.jpg",
  },
];

export default restList;
